service: serverless-demo

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: target/serverless-demo-1.0-SNAPSHOT.jar

functions:
  alignment:
    handler: no.uio.ifi.handlers.SmithWatermanHandler
    events:
      - http:
          path: alignment
          method: get
