package no.uio.ifi

import org.junit.Test
import kotlin.test.assertEquals

val EXPECTED_RESULT = """
MV-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKY
MVHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKY

""".trimIndent()


class SmithWatermanTest {

    @Test
    fun testGetAlignment() {
        val alignment = getAlignment("P69905", "P68871")
        LOGGER.info("alignment:\n{}", alignment)
        assertEquals(EXPECTED_RESULT, alignment)
    }

}
